name: Typescript SDK

on:
  workflow_call:
    inputs:
      slack-channel:
        description: |
          The Slack channel where the notification will be sent.
          Defaults to $ {{ github.event.repository.custom_properties.ci_slack_channel }}.
        required: false
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        description: The bot token used to authenticate with Slack.
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      is-release: ${{ steps.metadata.outputs.is-release }}
      publishable: ${{ steps.metadata.outputs.publishable }}
      version: ${{ steps.metadata.outputs.version }}
      npm-tag: ${{ steps.metadata.outputs.npm-tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup asdf-vm
        uses: equisoft-actions/with-asdf-vm@v2

      - name: Find application metadata
        id: metadata
        uses: equisoft-actions/nodejs-application-metadata@v1

      - name: Install NPM dependencies
        uses: equisoft-actions/yarn-install@v1


  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup asdf-vm
        uses: equisoft-actions/with-asdf-vm@v2

      - name: Install NPM dependencies
        uses: equisoft-actions/yarn-install@v1

      - name: Build
        run: yarn build

      - name: Store package
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1
          if-no-files-found: error

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs:
      - setup
      - build

    if: ${{ needs.setup.outputs.publishable == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist/

      - name: Setup asdf-vm
        uses: equisoft-actions/with-asdf-vm@v2

      - name: Install NPM dependencies
        uses: equisoft-actions/yarn-install@v1

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v5
        with:
          node-version-file: '.tool-versions'
          registry-url: 'https://registry.npmjs.org'

      - name: Update package version
        env:
          VERSION: ${{ needs.setup.outputs.version }}
        run: |
          contents="$(jq ".version = \"${VERSION}\"" ./package.json)" && echo "${contents}" > ./package.json

      - name: Publish to npmjs
        env:
          NPM_TAG: ${{ needs.setup.outputs.npm-tag }}
        run: |
          yarn npm publish --tag "${NPM_TAG}" --tolerate-republish --access public

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      - setup
      - build
      - publish
    if: always() && needs.setup.outputs.publishable == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Post workflow status
        uses: equisoft-actions/notify-workflow-status@v2
        with:
          needs: ${{ toJSON(needs) }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ inputs.slack-channel || github.event.repository.custom_properties.ci_slack_channel }}
